variable "instance_type" {}
variable "rhel_base_ami" {}
variable "SysName_tag" {}
variable "sec_grp_id" {}
variable "ssh_key_name" {}
variable "vpc_subnet_id" {}
variable "vpc_id" {}
variable "ssh_source_ip" {type="list"}
variable "hostname_tag" {}
variable "root_vol_size" {}
variable "root_vol_type" {}
variable "BusinessUnit" {}
variable "CostCenter" {}
variable "Environment" {}
variable "SysName" {}
variable "SysOwner" {}
variable "Department" {}
variable "tsm" {}
variable "instance_profile" {}
variable "PatchGroup" {}
variable "Scheduler" {}
